# Generated by Django 4.2.21 on 2025-05-22 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_tickettype_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registrated_at',
            new_name='registered_at',
        ),
        migrations.AddField(
            model_name='event',
            name='es_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.tickettype'),
        ),
    ]
